"""initial

Revision ID: e11ec6a63e1c
Revises: 
Create Date: 2022-12-30 23:33:25.485670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11ec6a63e1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_as_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_id'), 'date', ['id'], unique=False)
    op.create_table('rawdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.Column('data_open', sa.String(), nullable=True),
    sa.Column('data_high', sa.String(), nullable=True),
    sa.Column('data_low', sa.String(), nullable=True),
    sa.Column('data_close', sa.String(), nullable=True),
    sa.Column('data_volume', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rawdata_id'), 'rawdata', ['id'], unique=False)
    op.create_index(op.f('ix_rawdata_symbol'), 'rawdata', ['symbol'], unique=False)
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_id'), 'symbol', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_name'), 'symbol', ['name'], unique=False)
    op.create_table('daystats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('date_unique_id', sa.Integer(), nullable=True),
    sa.Column('day_open', sa.Float(), nullable=True),
    sa.Column('day_close', sa.Float(), nullable=True),
    sa.Column('day_volume', sa.Integer(), nullable=True),
    sa.Column('day_diff_percent', sa.Float(), nullable=True),
    sa.Column('time_high_cost', sa.DateTime(), nullable=True),
    sa.Column('time_low_cost', sa.DateTime(), nullable=True),
    sa.Column('time_high_volume', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['date_unique_id'], ['date.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daystats_id'), 'daystats', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('date_unique_id', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('data_open', sa.Float(), nullable=True),
    sa.Column('data_high', sa.Float(), nullable=True),
    sa.Column('data_low', sa.Float(), nullable=True),
    sa.Column('data_close', sa.Float(), nullable=True),
    sa.Column('data_volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_unique_id'], ['date.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_daystats_id'), table_name='daystats')
    op.drop_table('daystats')
    op.drop_index(op.f('ix_symbol_name'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_id'), table_name='symbol')
    op.drop_table('symbol')
    op.drop_index(op.f('ix_rawdata_symbol'), table_name='rawdata')
    op.drop_index(op.f('ix_rawdata_id'), table_name='rawdata')
    op.drop_table('rawdata')
    op.drop_index(op.f('ix_date_id'), table_name='date')
    op.drop_table('date')
    # ### end Alembic commands ###
